import java.awt.*;
import javax.swing.*;
import java.util.*;
import java.awt.Container;
import java.awt.Insets;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JFrame;

public class Accueil extends JFrame{

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bas = new javax.swing.JPanel();
        buttonGO = new javax.swing.JButton();
        haut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());

        bas.setBackground(new java.awt.Color(255, 255, 204));

        buttonGO.setBackground(new java.awt.Color(0, 0, 0));
        buttonGO.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        buttonGO.setForeground(new java.awt.Color(255, 255, 204));
        buttonGO.setText("GO!");
        buttonGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basLayout = new javax.swing.GroupLayout(bas);
        bas.setLayout(basLayout);
        basLayout.setHorizontalGroup(
        basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(basLayout.createSequentialGroup()
        .addGap(141, 141, 141)
                .addComponent(buttonGO, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        basLayout.setVerticalGroup(
            basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(buttonGO, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        //getContentPane().add(bas, new AbsoluteConstraints(0, 180, 700, 520));

        haut.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setText("HAPPY FRIGO");

        javax.swing.GroupLayout hautLayout = new javax.swing.GroupLayout(haut);
        haut.setLayout(hautLayout);
        hautLayout.setHorizontalGroup(
            hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hautLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        hautLayout.setVerticalGroup(
            hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hautLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        //getContentPane().add(haut, new AbsoluteConstraints(0, 0, -1, 180));

        pack();
    }// </editor-fold>                        

    private void buttonGOActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        RegimeAlimentaire f = new RegimeAlimentaire();
        f.setVisible(true);
        
        //pour cacher l'ancienne fenêtre
        this.hide();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel bas;
    private javax.swing.JButton buttonGO;
    private javax.swing.JPanel haut;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
