import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Allergie extends JFrame{

    /**
     * Creates new form Allergie
     */
    public Allergie() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelAllergie = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        allergieTexte = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        panelChoix = new javax.swing.JPanel();
        validerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAllergie.setBackground(new java.awt.Color(204, 204, 255));

        titre.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        titre.setText("ALLERGIES");

        allergieTexte.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        allergieTexte.setText("Allergie :");

        yesButton.setBackground(new java.awt.Color(0, 0, 0));
        yesButton.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        yesButton.setForeground(new java.awt.Color(204, 204, 255));
        yesButton.setText("Oui");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setBackground(new java.awt.Color(0, 0, 0));
        noButton.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        noButton.setForeground(new java.awt.Color(204, 204, 255));
        noButton.setText("Non");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        panelChoix.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelChoixLayout = new javax.swing.GroupLayout(panelChoix);
        panelChoix.setLayout(panelChoixLayout);
        panelChoixLayout.setHorizontalGroup(
            panelChoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelChoixLayout.setVerticalGroup(
            panelChoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        validerButton.setBackground(new java.awt.Color(0, 0, 0));
        validerButton.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        validerButton.setForeground(new java.awt.Color(204, 204, 255));
        validerButton.setText("Valider");

        javax.swing.GroupLayout panelAllergieLayout = new javax.swing.GroupLayout(panelAllergie);
        panelAllergie.setLayout(panelAllergieLayout);
        panelAllergieLayout.setHorizontalGroup(
            panelAllergieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChoix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAllergieLayout.createSequentialGroup()
                .addGroup(panelAllergieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAllergieLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(titre))
                    .addGroup(panelAllergieLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(allergieTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAllergieLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(validerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAllergieLayout.setVerticalGroup(
            panelAllergieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllergieLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panelAllergieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergieTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(panelChoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(validerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAllergie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAllergie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        AllergiePage2 p2 = new AllergiePage2();
        p2.setSize(700, 270);
        p2.setLocation(0,0);
        panelChoix.removeAll();
        panelChoix.add(p2, BorderLayout.CENTER);
        panelChoix.add(p2); 
        panelChoix.revalidate();
        panelChoix.repaint(); 
        validerButton.hide();
      
    }                                         

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Recette f = new Recette();
        f.setVisible(true);
        
        //pour cacher l'ancienne fenêtre
        this.hide();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Allergie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Allergie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Allergie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Allergie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Allergie().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel allergieTexte;
    private javax.swing.JButton noButton;
    private javax.swing.JPanel panelAllergie;
    private javax.swing.JPanel panelChoix;
    private javax.swing.JLabel titre;
    private javax.swing.JButton validerButton;
    private javax.swing.JButton yesButton;
    // End of variables declaration                   
}
