import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class AllergiePage2 extends JPanel{

    /**
     * Creates new form AllergiePage2
     */
    public boolean valide= false;
    public AllergiePage2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        contenu = new javax.swing.JPanel();
        glutenBox = new javax.swing.JCheckBox();
        lactoseBox = new javax.swing.JCheckBox();
        arachideBox = new javax.swing.JCheckBox();
        foodmapBox = new javax.swing.JCheckBox();
        oeufBox = new javax.swing.JCheckBox();
        autresBox = new javax.swing.JCheckBox();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenu.setBackground(new java.awt.Color(204, 204, 255));

        glutenBox.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        glutenBox.setText("Gluten");
        glutenBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glutenBoxActionPerformed(evt);
            }
        });

        lactoseBox.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lactoseBox.setText("Lactose");
        lactoseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lactoseBoxActionPerformed(evt);
            }
        });

        arachideBox.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        arachideBox.setText("Arachide");

        foodmapBox.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        foodmapBox.setText("Foodmap");
        foodmapBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodmapBoxActionPerformed(evt);
            }
        });

        oeufBox.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        oeufBox.setText("Oeuf");
        oeufBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oeufBoxActionPerformed(evt);
            }
        });

        autresBox.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        autresBox.setText("Autres");

        javax.swing.GroupLayout contenuLayout = new javax.swing.GroupLayout(contenu);
        contenu.setLayout(contenuLayout);
        contenuLayout.setHorizontalGroup(
            contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lactoseBox)
                    .addComponent(arachideBox)
                    .addComponent(glutenBox))
                .addGap(54, 54, 54)
                .addGroup(contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foodmapBox, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oeufBox)
                    .addComponent(autresBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenuLayout.setVerticalGroup(
            contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenuLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glutenBox)
                    .addComponent(foodmapBox))
                .addGap(38, 38, 38)
                .addGroup(contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lactoseBox)
                    .addComponent(oeufBox))
                .addGap(39, 39, 39)
                .addGroup(contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arachideBox)
                    .addComponent(autresBox))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        add(contenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -40, 480, 370));
    }// </editor-fold>                        

    private void glutenBoxActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void lactoseBoxActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void oeufBoxActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void foodmapBoxActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox arachideBox;
    private javax.swing.JCheckBox autresBox;
    private javax.swing.JPanel contenu;
    private javax.swing.JCheckBox foodmapBox;
    private javax.swing.JCheckBox glutenBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox lactoseBox;
    private javax.swing.JCheckBox oeufBox;
    // End of variables declaration                   
}
