import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Recette extends JFrame {

    /**
     * Creates new form Recette
     */
    public Recette() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        fond = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        francais = new javax.swing.JPanel();
        italien = new javax.swing.JPanel();
        asiatique = new javax.swing.JPanel();
        fastfood = new javax.swing.JPanel();
        petitdej = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fond.setBackground(new java.awt.Color(204, 255, 204));

        titre.setBackground(new java.awt.Color(255, 255, 255));
        titre.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        titre.setText("RECETTEs");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        francais.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout francaisLayout = new javax.swing.GroupLayout(francais);
        francais.setLayout(francaisLayout);
        francaisLayout.setHorizontalGroup(
            francaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        francaisLayout.setVerticalGroup(
            francaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Français", francais);

        italien.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout italienLayout = new javax.swing.GroupLayout(italien);
        italien.setLayout(italienLayout);
        italienLayout.setHorizontalGroup(
            italienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        italienLayout.setVerticalGroup(
            italienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Italien", italien);

        javax.swing.GroupLayout asiatiqueLayout = new javax.swing.GroupLayout(asiatique);
        asiatique.setLayout(asiatiqueLayout);
        asiatiqueLayout.setHorizontalGroup(
            asiatiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        asiatiqueLayout.setVerticalGroup(
            asiatiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Asiatique", asiatique);

        javax.swing.GroupLayout fastfoodLayout = new javax.swing.GroupLayout(fastfood);
        fastfood.setLayout(fastfoodLayout);
        fastfoodLayout.setHorizontalGroup(
            fastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        fastfoodLayout.setVerticalGroup(
            fastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fast-food", fastfood);

        javax.swing.GroupLayout petitdejLayout = new javax.swing.GroupLayout(petitdej);
        petitdej.setLayout(petitdejLayout);
        petitdejLayout.setHorizontalGroup(
            petitdejLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        petitdejLayout.setVerticalGroup(
            petitdejLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Petit déjeuner", petitdej);

        javax.swing.GroupLayout fondLayout = new javax.swing.GroupLayout(fond);
        fond.setLayout(fondLayout);
        fondLayout.setHorizontalGroup(
            fondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondLayout.createSequentialGroup()
                .addGroup(fondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(titre))
                    .addGroup(fondLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        fondLayout.setVerticalGroup(
            fondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recette().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel asiatique;
    private javax.swing.JPanel fastfood;
    private javax.swing.JPanel fond;
    private javax.swing.JPanel francais;
    private javax.swing.JPanel italien;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel petitdej;
    private javax.swing.JLabel titre;
    // End of variables declaration                   
}
