import java.awt.*;
import javax.swing.*;
import java.util.*;

public class RegimeAlimentaire extends JFrame{

    /**
     * Creates new form RegimeAlimentaire
     */
    public RegimeAlimentaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        fond = new javax.swing.JPanel();
        regimeAlimentaire = new javax.swing.JLabel();
        buttonOmnivore = new javax.swing.JButton();
        buttonVegetarian = new javax.swing.JButton();
        buttonVegan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fond.setBackground(new java.awt.Color(255, 204, 204));

        regimeAlimentaire.setBackground(new java.awt.Color(255, 204, 153));
        regimeAlimentaire.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        regimeAlimentaire.setText("Régime Alimentaire");
        regimeAlimentaire.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonOmnivore.setBackground(new java.awt.Color(0, 0, 0));
        buttonOmnivore.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        buttonOmnivore.setForeground(new java.awt.Color(255, 204, 204));
        buttonOmnivore.setText("Omnivore");
        buttonOmnivore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOmnivoreActionPerformed(evt);
            }
        });

        buttonVegetarian.setBackground(new java.awt.Color(0, 0, 0));
        buttonVegetarian.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        buttonVegetarian.setForeground(new java.awt.Color(255, 204, 204));
        buttonVegetarian.setText("Végétarian");
        buttonVegetarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVegetarianActionPerformed(evt);
            }
        });

        buttonVegan.setBackground(new java.awt.Color(0, 0, 0));
        buttonVegan.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        buttonVegan.setForeground(new java.awt.Color(255, 204, 204));
        buttonVegan.setText("Végan");
        buttonVegan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVeganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondLayout = new javax.swing.GroupLayout(fond);
        fond.setLayout(fondLayout);
        fondLayout.setHorizontalGroup(
            fondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(regimeAlimentaire)
                .addGap(92, 92, 92))
            .addGroup(fondLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(fondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonVegan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonVegetarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOmnivore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondLayout.setVerticalGroup(
            fondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(regimeAlimentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(buttonOmnivore, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(buttonVegetarian, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(buttonVegan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void buttonOmnivoreActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
        Allergie f = new Allergie();
        f.setVisible(true);
        
        //pour cacher l'ancienne fenêtre
        this.hide();
    }                                              

    private void buttonVegetarianActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        
        Allergie f = new Allergie();
        f.setVisible(true);
       
        this.hide();
    }                                                

    private void buttonVeganActionPerformed(java.awt.event.ActionEvent evt) {                                            
       Allergie f = new Allergie();
        f.setVisible(true);
        this.hide();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegimeAlimentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegimeAlimentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegimeAlimentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegimeAlimentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegimeAlimentaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonOmnivore;
    private javax.swing.JButton buttonVegan;
    private javax.swing.JButton buttonVegetarian;
    private javax.swing.JPanel fond;
    private javax.swing.JLabel regimeAlimentaire;
    // End of variables declaration                   
}
